// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvrAPkv3W1LXfpDURB_cTScBRuHEBkBT0',
    appId: '1:837721359628:web:1cf73d52ba7d03bf9385b2', // Placeholder for web ID
    messagingSenderId: '837721359628',
    projectId: 'floodguard-web',
    authDomain: 'floodguard-web.firebaseapp.com',
    storageBucket: 'floodguard-web.firebasestorage.app',
  );

  // Sourced from android/app/google-services.json (project floodguard-ai-6a9b6).
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi2CkqbKnWbq9RTi8nkaaqe3LAnBwabnY',
    appId: '1:274299040311:android:396bad82074bd83e9385b2',
    messagingSenderId: '274299040311',
    projectId: 'floodguard-ai-6a9b6',
    storageBucket: 'floodguard-ai-6a9b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvrAPkv3W1LXfpDURB_cTScBRuHEBkBT0',
    appId: '1:837721359628:ios:157e07f3917f991b9385b2',
    messagingSenderId: '837721359628',
    projectId: 'floodguard-web',
    storageBucket: 'floodguard-web.firebasestorage.app',
    iosBundleId: 'com.example.floodguardAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvrAPkv3W1LXfpDURB_cTScBRuHEBkBT0',
    appId: '1:837721359628:ios:157e07f3917f991b9385b2',
    messagingSenderId: '837721359628',
    projectId: 'floodguard-web',
    storageBucket: 'floodguard-web.firebasestorage.app',
    iosBundleId: 'com.example.floodguardAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvrAPkv3W1LXfpDURB_cTScBRuHEBkBT0',
    appId: '1:837721359628:web:ef55d816870a31199385b2',
    messagingSenderId: '837721359628',
    projectId: 'floodguard-web',
    authDomain: 'floodguard-web.firebaseapp.com',
    storageBucket: 'floodguard-web.firebasestorage.app',
  );
}
